### ISSUE TITLE
Zaza should support tests that are only run against some combinations

### ISSUE THREAD

**Issue by ChrisMacNaughton** [openstack-charmers/zaza#233]
It would be great if one could write tests that only are run on a subset of the gate/smoke/dev bundles, for example, I might want to validate that a service works correctly with loosing a member in an HA configuration, but killing the single unit of a service will break it.

I could imagine it looking something like:

```yaml
charm_name: api-example
tests:
  - zaza.openstack.charm_tests.api.api_test
  - zaza.openstack.charm_tests.api.ha_test:
        only: [ ha ]
  - zaza.openstack.charm_tests.api.single_unit_lost:
        not: [ ha ]
configure: []
gate_bundles:
  - ha
  - basic
smoke_bundles:
  - basic
```

While this would, marginally, complicate the parsing of tests, I think that adding optional configuration to the test runs could end up being valuable in a number of scenarios.

For reference, the above YAML gets parsed into a Dict that looks like:

```python
{
    'charm_name': 'api-example',
    'configure': [],
    'gate_bundles': ['ha', 'basic'],
    'smoke_bundles': ['basic'],
    'tests': ['zaza.openstack.charm_tests.api.api_test',
              {'zaza.openstack.charm_tests.api.ha_test': {'only': ['ha']}},
              {'zaza.openstack.charm_tests.api.single_unit_lost': {'not': ['ha']}}]}
```

**Comment by gnuoy** [comment]
This is now possible using model aliases. The tests.yaml for the use case in the bug description would be:

```
charm_name: api-example
tests:
  - zaza.openstack.charm_tests.api.api_test
  - ha:
    - zaza.openstack.charm_tests.api.ha_test:
  - not_ha:
    - zaza.openstack.charm_tests.api.single_unit_lost:
configure: []
gate_bundles:
  - ha: ha
  - not_ha: basic
smoke_bundles:
  - not_ha: basic
```
