### ISSUE TITLE
Handle secrets and local config

### ISSUE THREAD

**Issue by gnuoy** [openstack-charmers/zaza#277]
It would be useful if zaza looked for a local config file and loaded config from it rather than relying on environment variables. The config file could also store secrets that should not be exposed in logs. My current thinking is something like:

**~/.zaza.yaml**

```
provider_secrets:
  OS_AUTH_URL: http://100.10.10.10:5000/v3
  OS_USERNAME: bob
  OS_PASSWORD: password
  OS_USER_DOMAIN_NAME: user
  OS_PROJECT_NAME: bobproj
  OS_PROJECT_ID: a5cb900
  OS_PROJECT_DOMAIN_NAME: user
  OS_AUTH_VERSION: 3
  OS_IDENTITY_API_VERSION: 3
  OS_REGION_NAME: serverstack
runtime_config:
  OS_VAR: 10.100.12.3
  http_proxy: http://squid
secrets:
  NAS_PASSWORD: hardpassword
```
