### ISSUE TITLE
Docs don't seem to clearly explain about model-specific tests

### ISSUE THREAD

**Issue by Vultaire** [openstack-charmers/zaza#343]
Hello,

During a code review today, I noted a peer using model-specific tests, e.g.:

```yaml
tests:
  - model_alias_xenial:
      - tests.tests_mongodb.BasicMongodbCharmTest
      - tests.tests_mongodb.ReplicatedMongodbCharmTest
      - tests.tests_mongodb.XenialMongodbCharmTest
  - model_alias_bionic:
      - tests.tests_mongodb.BasicMongodbCharmTest
      - tests.tests_mongodb.ReplicatedMongodbCharmTest
  - model_alias_shard:
      - tests.tests_mongodb.ShardedMongodbCharmTest
```

I tried to find an example of this usage in the docs, but wasn't able to readily find it.  I feel like it ought to be called out in docs/source/addingcharmtests.rst.
