### ISSUE TITLE
Support model maps on target_deploy_status

### ISSUE THREAD

**Issue by auria** [openstack-charmers/zaza#370]
Environment deploys such as `gate_bundles`, `smoke_bundles` and `dev_bundles`, as well as the `configure` and `tests` sections support model aliasing. All items mapped to a model alias will be deployed, configured and tested.

However, `target_deploy_status` section does not support model maps yet. Adding support would mean that depending on the deployed bundle, the expectation would be that an application will be in one or another workload state (active, blocked), showing one or another workload status message (`Unit is ready` or `Missing relations:`).

The implementation would need to support the current configurations as well as a list of model aliases.
 * If `target_deploy_status` can be loaded as a dict, it means it has the current format (no model maps).
 * If `target_deploy_status` can be loaded as a list, it means it has the new format (model maps starting with a hyphen)
  * a reserved keyword such as `__ALL__` or `default` could give default workload values to the defined applications

```yaml
target_deploy_status:
  - tls:
      vault:
        workload-status: blocked
        workload-status-message: Missing
  - __ALL__:
    nova-cloud-controller:
      workload-status: blocked
      workload-status-message: Missing
```

**Comment by auria** [comment]
In order to use the same format as in the other sections, the yaml format should be:
```yaml
target_deploy_status:
  - bionic:
      vault:
        workload-status: blocked
        workload-status-message: Missing
  - nova-cloud-controller:
      workload-status: blocked
      workload-status-message: Missing
```

Where `bionic` would be a model alias and `vault` and `nova-cloud-controller` would be application names.

**Comment by gnuoy** [comment]
+1 Sounds like a useful addition

**Comment by auria** [comment]
Changes can be found at:
 * https://github.com/auria/zaza/commit/d66085fa9f7692c35e039925fc5152a5d9edc729
 * https://github.com/auria/zaza-openstack-tests/commit/d10f528d039d8aec79e3d8c293cd02e7e95ca809

No PRs yet because testing is under way. So far, cinder smoke test was run as expected, using https://github.com/openstack-charmers/zaza-openstack-tests/pull/372 and the following `tests.yaml`:
```
charm_name: cinder
smoke_bundles:
  - bionic-train
gate_bundles:
  - focal-ussuri
  - tls: focal-ussuri-volume-only
  - bionic-ussuri
  - bionic-train
  - bionic-stein
  - bionic-rocky
  - bionic-queens
  - xenial-queens
  - xenial-ocata
  - xenial-pike
  - xenial-mitaka
  - trusty-mitaka
dev_bundles:
- groovy-victoria
- focal-victoria
target_deploy_status:
  - tls:
      vault:
        workload-status: blocked
        workload-status-message: Vault needs to be initialized
configure:
  - zaza.openstack.charm_tests.glance.setup.add_cirros_image
  - zaza.openstack.charm_tests.glance.setup.add_lts_image
  - zaza.openstack.charm_tests.keystone.setup.add_demo_user
  - tls:
      - zaza.openstack.charm_tests.vault.setup.auto_initialize
      - zaza.openstack.charm_tests.glance.setup.add_cirros_image
      - zaza.openstack.charm_tests.glance.setup.add_lts_image
      - zaza.openstack.charm_tests.keystone.setup.add_demo_user
tests:
  - zaza.openstack.charm_tests.cinder.tests.CinderTests
  - zaza.openstack.charm_tests.cinder.tests.SecurityTests
  - zaza.openstack.charm_tests.policyd.tests.CinderTests
  - tls:
      - zaza.openstack.charm_tests.cinder.tests.CinderTests
      - zaza.openstack.charm_tests.cinder.tests.TLSSecurityTests
      - zaza.openstack.charm_tests.policyd.tests.CinderTests
tests_options:
  policyd:
    service: cinder
  force_deploy:
    - groovy-victoria
```
Note: `target_deploy_status` format slightly changed for the purpose.
