### ISSUE TITLE
local_overlay support for charmcraft built charms

### ISSUE THREAD

**Issue by freyes** [openstack-charmers/zaza#579]
Charms that define multiple bases can produce multiple output files with long names (e.g. octavia_ubuntu-20.04_ubuntu-22.04.charm), this makes more time consuming to have the testing bundles right, but also you have to keep them updated as bases get dropped and added to enable new ubuntu series.

It would be nice if the local_overlay flag could programmatically detect what's the right charm for a bundle, it would be necessary to read the `series` key in the bundle, at the top level and at the application level, e.g:

```yaml
series: jammy
applications:
  keystone:
    charm: ch:keystone
    series: jammy
```

^ in this case the overlay generated should look something like this:

```yaml
applications:
  keystone:
    charm: "../../keystone_ubuntu-22.04-amd64_ubuntu-22.10-amd64.charm
```
